version: "3"

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
