version: '3.6'

services:
  eventstore:
    image: eventstore/eventstore:latest
    ports:
      - 1113:1113
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
    labels:
      - 'traefik.docker.network=web'
      - 'traefik.enable=true'
      - 'traefik.basic.frontend.rule=Host:eventstore.developer.local'
      - 'traefik.basic.port=2113'
      - 'traefik.basic.protocol=http'
    networks:
      - web
      - default

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    labels:
      - 'traefik.docker.network=web'
      - 'traefik.enable=true'
      - 'traefik.basic.frontend.rule=Host:mongo.developer.local'
      - 'traefik.basic.port=8081'
      - 'traefik.basic.protocol=http'
    networks:
      - web
      - default

networks:
  web:
    external: true
