version: '3.6'

services:
  eventstore.db:
    image: eventstore/eventstore:20.10.2-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - '1113:1113'
      - '2113:2113'
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: mongo-volume-data
        target: /data/db

  mongoclient:
    image: mongoclient/mongoclient
    ports:
      - 3000:3000
    volumes:
      - type: volume
        source: mongoclient-volume-data
        target: /data/db
    environment:
      - MONGO_URL=mongodb://mongo:27017/mongoclient

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
  mongo-volume-data:
  mongoclient-volume-data:
